### PR TITLE
feat: @typescript-eslint/member-ordering

### PR DESCRIPTION
**Pull request by youKnowOwO**
This pull req will sort member ordering in a class

### CODE REVIEW

**Comment by Hazmi35** [comment]
Ini orderingnya berdasarkan di array?

**Comment by youKnowOwO** [comment]
Hooh

**Comment by Hazmi35** [comment]
gak di buat beberapa selain default? welp kalo mau gini doang silahkan aja

**Review by Hazmi35 — APPROVED** [review]

**Review by Waxaranai — COMMENTED** [review]
Gw gak paham apa2

**Comment by youKnowOwO** [comment]
As you see member orderingnya musti short sesuai confignya
Misal
```ts
private foo = "foo";
public bar = "bar";
```
^ini bakalan error karena sesudah private member gk boleh ada public member
Makanya musti `public` dulu baru `private`
```ts
public bar = "bar";
private foo = "foo";
```

**Review by Waxaranai — APPROVED** [review]
Oke, gak masalah sih. biar rapi juga

**Comment by Hazmi35** [comment]
Let's wait for Sharif's review then you can merge this to master, don't forget to create a release after that, bump the version first

**Comment by SharifPoetra** [comment]
Looks good for me, but this will make a lot of end-user code changes so I recommend this to minor release.

**Comment by Hazmi35** [comment]
Alright, just upgrade @mizudev/eslint-config when you're ready, this pull request seems ready, I'll release this as 1.4.0

**Pull request merged**
